#!/usr/bin/env  bash
# Author:       Casey Sparks
# Date:         February 6, 2025
# Description:  Global pre-commit hooks.
# Shellcheck:
# shellcheck    disable=SC1091 # Not following venv dir
# shellcheck    disable=SC2034 # $GIT_DIR used by `git`

REPO_DIR="$(git rev-parse --show-toplevel)"
GIT_DIR="$(git rev-parse --absolute-git-dir)"
PY_VER='3.11'
EXTENSIONS=(
    'dot' 'gv'
    'md' 'markdown'
    'py'
    'tf' 'hcl'
    'xml' 'mobileconfig'
    'yaml' 'yml'
)

cd "${REPO_DIR}" || exit 1

log(){
    local LEVEL="${1:?}"    # Log level
    local MSG="${2:?}"      # Log message
    local CLR='\033[0m'     # No color
    local GRN='\033[0;32m'  # Green
    local YLW='\033[0;33m'  # Yellow
    local RED='\033[0;31m'  # Red
    local OUT=1             # STDOUT
    local COLOR="${CLR}"    # Default log message color

    # ANSI color codes
    case "${LEVEL}" in
        'INFO')
            COLOR="${GRN}"
            ;;
        "WARN*")
            COLOR="${YLW}"
            ;;
        "ERR*")
            COLOR="${YLW}"
            OUT=2
            ;;
        "CRIT*|FATAL")
            COLOR="${RED}"
            OUT=2
            ;;
    esac

    printf '%b%-10s %-80s%b\n' "${COLOR}" "${LEVEL}" "${MSG}" "${CLR}" >&"${OUT}"

    if [ "${LEVEL}" == 'FATAL' ]; then # Exit on fatal
        log DEBUG 'Exiting.'
        exit 1
    fi
}

venv_activate(){
    if ! git diff HEAD --exit-code -- **/*.py > /dev/null 2>&1; then
        case "${VIRTUAL_ENV:-}" in
            "${VENV_DIR}")  return          ;; # Exit early if venv active
            '')             true            ;; # Do nothing if no venv
            "*")            venv_deactivate ;; # Deactivate other venv
        esac

        if [ -f "${VENV_DIR}/bin/activate" ]; then # Script exists
            log DEBUG "Activating existing virtual environment: ${VENV_DIR}/"
            source "${VENV_DIR}/bin/activate"
        elif [ ! -d "${VENV_DIR}" ]; then # Script does not exist, dir does not exist
            # Create and activate virtual environment
            log DEBUG 'Creating Python virtual environment.'
            "python${PY_VER}" -m venv "${VENV_DIR}"
            venv_activate
        else # Script does not exist, dir DOES exist
            log FATAL "${VENV_DIR}/ exists, but is not a Python virtual environment."
        fi
    fi

    pip install --upgrade pip
}

venv_deactivate(){
    log DEBUG 'Deactivating Python virtual environment'

    if [ -n "${_OLD_VIRTUAL_PATH:-}" ]; then
        PATH="${_OLD_VIRTUAL_PATH:-}"
        export PATH
        unset _OLD_VIRTUAL_PATH
    fi

    if [ -n "${_OLD_VIRTUAL_PYTHONHOME:-}" ]; then
        PYTHONHOME="${_OLD_VIRTUAL_PYTHONHOME:-}"
        export PYTHONHOME
        unset _OLD_VIRTUAL_PYTHONHOME
    fi

    # Call hash to forget past commands.
    hash -r 2> /dev/null

    if [ -n "${_OLD_VIRTUAL_PS1:-}" ]; then
        PS1="${_OLD_VIRTUAL_PS1:-}"
        export PS1
        unset _OLD_VIRTUAL_PS1
    fi

    unset VIRTUAL_ENV
    unset VIRTUAL_ENV_PROMPT
    unset -f deactivate
}

precommit_ansible(){ # TODO: find a way to call this
    ANSIBLE_DIR="${GIT_DIR}/ansible"
    VENV_DIR="${ANSIBLE_DIR}/.venv"

    cd "${ANSIBLE_DIR}" || exit 1

    venv_activate
    ansible-lint "${ANSIBLE_DIR}"
    venv_deactivate

    unset VENV_DIR
    cd "${REPO_DIR}" || exit 1
}

precommit_dot(){
    if which -s dot; then
        log DEBUG 'Running Graphviz pre-commit steps'
        log INFO "dot -P ${*}"

        dot -P "${@}" >&1 > /dev/null || log CRITICAL 'graphviz check failed'
    else log CRITICAL 'dot not installed'
    fi
}

precommit_gv(){ precommit_dot "${@}"; }

precommit_md(){
    log DEBUG 'Running Markdown pre-commit steps'

    if which -s mdl; then
        mdl "${@}" || log CRITICAL 'mdl check failed'
    else log CRITICAL 'mdl not installed. Skipping.'
    fi
}

precommit_markdown(){ precommit_md "${@}"; }

precommit_py(){
    VENV_DIR="${REPO_DIR}/.venv"

    log DEBUG 'Running Python pre-commit steps'
    venv_activate

    # pip-audit
    pip-audit "${REPO_DIR}"

    # ruff
    if which -s ruff; then
        log INFO 'ruff check'
        ruff check "${@}" || log CRITICAL 'ruff check failed'

        log INFO 'ruff format --check'
        ruff format --check "${@}" || log CRITICAL 'ruff format check failed'
    else log CRITICAL 'ruff not installed'
    fi

    # mypy
    if which -s mypy; then
        log INFO 'mypy'
        mypy --config-file "${REPO_DIR}/.mypy.ini" "${@}" || log CRITICAL 'mypy check failed'
    else log CRITICAL 'mypy not installed'
    fi

    # pytest
    if which -s pytest; then
        log INFO 'pytest'
        pytest "${@}" || log CRITICAL 'pytest failed'
    else log CRITICAL 'pytest not installed'
    fi

    venv_deactivate

    unset VENV_DIR
}

precommit_tf(){
    local TF_MNFSTS=() # This is a set
    local TF_MDLS=() # This is a set
    local PARENT_DIR

    if which -s terraform; then # Terraform
        log INFO 'Finding Terraform directories'

        for FILE in "${@}"; do # All files ending with *.{tf,hcl}
            PARENT_DIR="$(dirname "${FILE}")"

            case "${PARENT_DIR}" in
                *'/terraform/modules/'*) # Find module directories
                    PARENT_DIR="${PARENT_DIR/'tests'*}"

                    if ! printf '%s\n' "${TF_MDLS[@]}" | grep -q --line-regexp --fixed-strings "${PARENT_DIR}"; then
                        TF_MDLS+=("${TF_MDLS[@]}" "${PARENT_DIR}")
                    fi
                    ;;
                *) # Find manifest directories
                    if ! printf '%s\n' "${TF_MNFSTS[@]}" | grep -q --line-regexp --fixed-strings "${PARENT_DIR}"; then
                        TF_MNFSTS+=("${TF_MNFSTS[@]}" "${PARENT_DIR}")
                    fi
                    ;;
            esac
        done

        log DEBUG "Found ${#TF_MNFSTS[@]} Terraform manifest directories: ${TF_MNFSTS[*]}"
        log DEBUG "Found ${#TF_MDLS[@]} Terraform modules: ${TF_MDLS[*]}"

        log DEBUG 'Running Terraform pre-commit steps'

        log INFO 'terraform fmt --recursive'
        terraform -chdir="${REPO_DIR}/terraform" fmt --recursive

        # Validate manifests
        for MANIFEST in "${TF_MNFSTS[@]}"; do
            log INFO "terraform validate ${MANIFEST}"
            terraform -chdir="${MANIFEST}" validate || log CRITICAL 'terraform validation failed'
        done

        # Test modules
        for MODULE in "${TF_MDLS[@]}"; do
            log INFO "terraform test ${MODULE}"

            terraform -chdir="${MODULE}" test || log CRITICAL 'terraform tests failed'
        done
    else log CRITICAL 'terraform not installed. Skipping.'
    fi

    if which -s trivy; then # Trivy
        log INFO 'Running trivy pre-commit steps'

        for TF_DIR in "${TF_MNFSTS[@]}" "${TF_MDLS[@]}"; do
            log INFO "trivy config ${TF_DIR}"
            trivy conf "${TF_DIR}"
        done
    else log CRITICAL 'trivy not installed. Skipping.'
    fi
}

precommit_hcl(){ precommit_tf "${@}"; }

precommit_sh(){
    if which -s shellcheck; then
        shellcheck "${@}" || log CRITICAL 'shellcheck failed'
    else log CRITICAL 'shellcheck not installed. Skipping.'
    fi
}

precommit_bash(){ precommit_sh "${@}"; }

precommit_yaml(){
    if which -s yamllint; then
        yamllint --config-file "${REPO_DIR}/.yamllint.yml" "${@}" || log CRITICAL 'yamllint failed'
    else log CRITICAL 'yamllint not installed. Skipping.'
    fi
}

precommit_yml(){ precommit_yaml "${@}"; }

pre_check(){
    log INFO 'Running repository pre-commit hooks.'
}

run_hook(){
    # Find files by extension
    for EXTENSION in "${EXTENSIONS[@]}"; do
        readarray -t EXTENSION_FILES < <( # Array of files ending with extension
            git status --porcelain                                      |
            awk -v dir="${REPO_DIR}" '$1 ~/^[AM??]/ {print dir"/"$2}'   |
            grep --extended-regexp "^.*\.${EXTENSION}$"
        )

        # Run relevant function for extension
        if [ "${#EXTENSION_FILES[@]}" -ge 1 ]; then
            "precommit_${EXTENSION}" "${EXTENSION_FILES[@]}"
        fi
    done
}

post_check(){
    log INFO 'Precommit checks completed successfully. Exiting.'
}

pre_check
run_hook
post_check
