[pytest]
minversion = "9.0"
testpaths = ["."]
addopts = [
    "--cov=.",
    "--cov-fail-under=95",
    "--cov-report=term-missing",
    "--pdbcls=IPython.terminal.debugger:TerminalPdb",
]
norecursedirs = [
    "ansible/collections/caseysparkz/environment/roles/vim/files/vim/pack/plugins/start",
    ".dagger/src/*",
]
