[project]
name = "cs-monorepo"
description = "Global installer for the monorepo."
requires-python = ">=3.13"
version = "0.1.0"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [{ name = "CaseySparkz", email = "contact@caseysparkz.com" }]
dependencies = [
    "cs-ansible @ file:./ansible",
    "boto3==1.43.83",
]

[project.optional-dependencies]
test = [
    "cs-ansible[test]",

    "boto3-stubs==1.43.80",
    "botocore-stubs==1.43.67",
    "ipdb==0.13.13",
    "moto==5.2.3",
    "mypy==2.3.1",
    "pip-audit==2.10.1",
    "pytest-cov==7.1.0",
    "pytest==9.1.1",
    "ruff==0.16.5",
    "types-boto3[ses]",
    "yamllint==1.38.0",
]
dev = [
    "cs-monorepo[test]",

    "ipython==9.16.1",
]
all = [
    "cs-ansible[all]",

    "cs-monorepo[dev]",
    "cs-monorepo[test]",
]

[tool.setuptools.packages.find]
where = []

[build-system]
build-backend = "setuptools.build_meta"
requires-python = ">= 3.13"
requires = ["setuptools"]

# Tools ========================================================================
# Misc. -----------------------------------------------------------------------
[tool.ipdb]
context = 20
