---
version: "0.1"
projects:
  - &default
    name: "/tfstate/"
    path: "./state/"
    skip_autodetect: false
    terraform_workspace: "default"
    usage_file: "./state/infracost_usage.yml"
    terraform_var_files: []
    dependency_paths: []

  - <<: *default
    name: "caseysparkz.com"
    path: "./manifests/com/caseysparkz/"
    usage_file: "./manifests/com/caseysparkz/infracost_usage.yml"
    terraform_var_files: ["./production.tfvars"]
    dependency_paths:
      - "./manifests/com/caseysparkz/**"
      - "./modules/proton_domain/**"

  - <<: *default
    name: "ecr.caseysparkz.com"
    path: "./manifests/com/caseysparkz/ecr/"
    usage_file: "./manifests/com/caseysparkz/ecr/infracost_usage.yml"
    dependency_paths:
      - "./manifests/com/caseysparkz/ecr/**"
      - "./modules/ecr/**"

  - <<: *default
    name: "store.caseysparkz.com"
    path: "./manifests/com/caseysparkz/store/"
    usage_file: "./manifests/com/caseysparkz/store/infracost_usage.yml"

  - <<: *default
    name: "www.caseysparkz.com"
    path: "./manifests/com/caseysparkz/www/"
    usage_file: "./manifests/com/caseysparkz/www/infracost_usage.yml"
    dependency_paths:
      - "./manifests/com/caseysparkz/www/**"
      - "./modules/hugo_static_site/**"
      - "./modules/s3_artifacts/**"
