# Author:       Casey Sparks
# Date:         March 4, 2026
# Description:  Configuration file for workflows using the <tj-actions/changed-files> action.
---
ansible:
  - "ansible/**/*.yaml"
  - "ansible/**/*.yml"
github: [".github/**"]
go:
  - "**/*.go"
  - "**/go.mod"
  - "**/go.sum"
graphviz:
  - "**/*.dot"
  - "**/*.gv"
infracost: ["terraform/**/infracost*.yml"]
markdown: ["**/*.md"]
python:
  - "**/*.py"
  - "**/pylock.toml"
  - "**/pyproject.toml"
jinja: ["**/*.j2"]
shell:
  - "**/*.bash"
  - "**/*.sh"
  - "./.githooks/*"
tfmanifest:
  - "infra/manifests/**/*.hcl"
  - "infra/manifests/**/*.tf"
  - "infra/manifests/**/*.tf.json"
  - "infra/manifests/**/*.tftpl"
  - "infra/manifests/**/*.tfvars"
  - "infra/manifests/**/*.tfvars.json"
  - "infra/manifests/**/.terraform.lock.hcl"
  - "infra/manifests/**/tfvars/*"
  - "infra/manifests/*.tf"
tfmodule:
  - "infra/modules/**/*.hcl"
  - "infra/modules/**/*.json"
  - "infra/modules/**/*.tf"
  - "infra/modules/**/*.tftest.*"
  - "infra/modules/**/.terraform.lock.hcl"
xml:
  - "**/*.svg"
  - "**/*.xml"
yaml:
  - "**/*.yaml"
  - "**/*.yml"
  - "ansible/.ansible-lint"
