---
packages_apt:
  - "containerd.io"
  - "dirmngr"
  - "dnsutils"
  - "docker-buildx-plugin"
  - "docker-ce"
  - "docker-ce-cli"
  - "docker-compose-plugin"
  - "firefox-esr"
  - "fwupd"
  - "gnupg-agent"
  - "gnupg2"
  - "libpam-u2f"
  - "libpam-yubico"
  - "modemmanager"
  - "net-tools"
  - "network-manager"
  - "nmap"
  - "pamu2fcfg"
  - "pcscd"
  - "scdaemon"
  - "wget"
  - "yubikey-manager"
  - "yubikey-personalization"
packages_homebrew:
  - "bash-completion@2"
  - "colima"
  - "coreutils"
  - "docker"
  - "docker-agent"
  - "docker-buildx"
  - "docker-completion"
  - "docker-compose"
  - "docker-credential-helper"
  - "dos2unix"
  - "gh"
  - "git"
  - "gnupg"
  - "gnupg-pkcs11-scd"
  - "graphviz"
  - "hadolint"
  - "hashicorp/tap/terraform"
  - "infracost"
  - "iproute2mac"
  - "ipython"
  - "jq"
  - "lima-additional-guestagents"
  - "markdownlint-cli2"
  - "pinentry-mac"
  - "pnpm"
  - "python@3.10"
  - "python@3.11"
  - "python@3.13"
  - "shellcheck"
  - "tfschema"
  - "thefuck"
  - "tldr"
  - "tree"
  - "trivy"
  - "virtualenv"
  - "watch"
  - "wget"
  - "yamllint"
