---
- name: "Install system packages [apt]"
  become: true
  when: "ansible_facts.os_family == 'Debian'"
  tags: ["apt"]
  ansible.builtin.apt:
    pkg: "{{ packages_apt }}"
    state: "present"
    update_cache: true
    cache_valid_time: 3600

- name: "Install system packages [brew]"
  when: "ansible_facts.os_family == 'Darwin'"
  tags: ["brew"]
  community.general.homebrew:
    name: "{{ packages_homebrew }}"
    state: "present"
    update_homebrew: true
