---
apiVersion: "v1"
kind: "List"
metadata:
  resourceVersion: ""
  selfLink: ""
items:
  - apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "etcd"
      namespace: "etcd"
    spec:
      clusterIP: "None"
      clusterIPs: ["None"]
      internalTrafficPolicy: "Cluster"
      ipFamilies: ["IPv4"]
      ipFamilyPolicy: "SingleStack"
      ports:
        - name: "etcd-client"
          port: 2379
          protocol: "TCP"
          targetPort: 2379
        - name: "etcd-server"
          port: 2380
          protocol: "TCP"
          targetPort: 2380
        - name: "etcd-metrics"
          port: 8080
          protocol: "TCP"
          targetPort: 8080
      publishNotReadyAddresses: true
      selector:
        app: "etcd"
      sessionAffinity: "None"
      type: "ClusterIP"
    status:
      loadBalancer: {}
