#!/usr/bin/env sh
# Author:       Casey Sparks
# Date:         May 30, 2026
# Description:  Retrieve the vault password from AWS SecretsManager.

# Check if AWS CLI is installed
if ! which aws > /dev/null 2>&1; then
   printf 'AWS CLI not installed.\n' >&2
   exit 1
fi

# Check we're authenticated
if ! aws sts get-caller-identity > /dev/null 2>&1 ; then
    printf 'Not logged in to AWS CLI.\n' >&2
    exit 1
fi

# Retreive secret to STDOUT
aws secretsmanager get-secret-value                                         \
    --region us-west-2                                                      \
    --secret-id ansible/vault                                               \
    --query SecretString                                                    \
    --output text                                                           \
    --no-cli-pager                                                          \
