---
- name: "Create ~/.ssh/{,keys/}"
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.ssh/keys/"
    state: "directory"
    mode: "0700"

- name: "Write ~/.ssh/config"
  ansible.builtin.copy:
    src: "config"
    dest: "{{ ansible_facts.env.HOME }}/.ssh/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
    force: false
