# Author:       Casey Sparks
# Date:         November 15, 2023
# Description:  Run ansible-lint against Ansible configs on push and PR.
---
name: "ansible"
on:
  pull_request:
    branches: ["main"]
    paths:
      - "collections/**/*.yml"
      - "hosts/**/*.yml"
      - "playbooks/**/*.yml"
    types:
      - "opened"
      - "ready_for_review"
      - "reopened"
      - "synchronize"
jobs:
  ansible_lint:
    name: "ansible-lint"
    runs-on: "ubuntu-latest"
    env:
      ANSIBLE_CACHE_KEY: "ansible-cache"
      ANSIBLE_CACHE_PATH: "${{ github.workspace }}/ansible/collections/ansible_collections/"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0"  # v7.0.0
        with:
          fetch-depth: 0

      - name: "Restore Ansible cache"
        id: "ansible-cache"
        uses: "actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9"  # v6.1.0
        with:
          key: "${{ env.ANSIBLE_CACHE_KEY }}"
          path: "${{ env.ANSIBLE_CACHE_PATH }}"

      - name: "Run ansible-lint"
        uses: "ansible/ansible-lint@262624cd0ab22a4221293216856c59671ce7aa5e"  # v26.6.0
        with:
          args: ""
          working_directory: "${{ github.workspace }}/ansible/"
          requirements_file: "requirements.yml"
          setup_python: true

      - name: "Save Ansible cache"
        uses: "actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9"  # v6.1.0
        with:
          key: "${{ steps.ansible-cache.outputs.cache-primary-key }}"
          path: "${{ env.ANSIBLE_CACHE_PATH }}"
