# Author:       Casey Sparks
# Date:         November 15, 2023
# Description:  Run dagger checks.
---
name: "CI"
on:
  pull_request:
    branches: ["main"]
env:
  AWS_DEFAULT_REGION: "us-west-2"
  DO_NOT_TRACK: "1"  # Disable Dagger telemetry
  DAGGER_VERSION: "latest"
jobs:
  dagger_check:
    name: "dagger"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
      pull-requests: "write"
    steps:
      - name: "git checkout"
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
        with:
          ref: "${{ github.event.pull_request.head.ref }}"  # Explicitly check out branch by name
          fetch-depth: 2

      - name: "git diff ${{ github.base.ref }} --name-only"
        id: "changed_files"
        uses: "tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96" # 47.0.6
        with:
          files_yaml_from_source_file: ".github/config/changed_files.yml"
          matrix: true

      - name: "aws sso login"
        uses: "aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c"  # v6.2.4
        with:
          aws-region: "${{ env.AWS_DEFAULT_REGION }}"
          role-to-assume: "${{ secrets.AWS_ROLE_ARN }}"
          role-session-name: "gha-${{ github.run_id }}"

      - name: "aws ecr get-login-password | docker login -u AWS --password-stdin"
        uses: "aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd"  # v2.1.7

      - name: "export DAGGER_CLOUD_TOKEN=$(aws secretsmanager get-secret-value --secret-id dagger/api_token)"
        uses: "aws-actions/aws-secretsmanager-get-secrets@2cb1a461cbd4865ac4299648312e4704c646cd53"  # v3.0.1
        with:
          secret-ids: "DAGGER_CLOUD_TOKEN, dagger/api_token"
          name-transformation: "none"
          parse-json-secrets: false
          auto-select-family-attempt-timeout: 500

      - name: "dagger check ansible:*"
        if: "${{ steps.changed_files.outputs.ansible_any_changed == 'true' }}"
        uses: "dagger/checks@64525befa1c36dd55577dae083df5c8968d9325a"  # v1.1.0
        with:
          filter: "ansible:*"
          version: "${{ env.DAGGER_VERSION }}"
          cloud-token: "${{ env.DAGGER_CLOUD_TOKEN }}"

      - name: "dagger check github:*"
        uses: "dagger/checks@64525befa1c36dd55577dae083df5c8968d9325a"  # v1.1.0
        env:
          GITHUB_TOKEN: "${{ github.token }}"
        with:
          filter: "github:*"
          version: "${{ env.DAGGER_VERSION }}"
          cloud-token: "${{ env.DAGGER_CLOUD_TOKEN }}"

      - name: "dagger check python:*"
        if: "${{ steps.changed_files.outputs.python_any_changed == 'true' }}"
        uses: "dagger/checks@64525befa1c36dd55577dae083df5c8968d9325a"  # v1.1.0
        with:
          filter: "python:*"
          version: "${{ env.DAGGER_VERSION }}"
          cloud-token: "${{ env.DAGGER_CLOUD_TOKEN }}"

      - name: "dagger check terraform:*"
        if: "${{ steps.changed_files.outputs.terraform_any_changed == 'true' }}"
        uses: "dagger/checks@64525befa1c36dd55577dae083df5c8968d9325a"  # v1.1.0
        with:
          filter: "terraform:*"
          version: "${{ env.DAGGER_VERSION }}"
          cloud-token: "${{ env.DAGGER_CLOUD_TOKEN }}"

      - name: "dagger check yaml:*"
        if: "${{ steps.changed_files.outputs.yaml_any_changed == 'true' }}"
        uses: "dagger/checks@64525befa1c36dd55577dae083df5c8968d9325a"  # v1.1.0
        with:
          filter: "yaml:*"
          version: "${{ env.DAGGER_VERSION }}"
          cloud-token: "${{ env.DAGGER_CLOUD_TOKEN }}"
