# Author:       Casey Sparks
# Date:         November 22, 2024
# Description:  Lint all markdown files with mdl (mdlint).
---
name: "markdown"
on:
  pull_request:
    branches: ["main"]
jobs:
  mdl:
    name: "mdl"
    runs-on: "ubuntu-latest"
    steps:
      - name: "git checkout"
        uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0"  # v7.0.0
        with:
          fetch-depth: 0

      - name: "mdl"
        uses: "actionshub/markdownlint@6c82ff529253530dfbf75c37570876c52692835f"  # v3.1.4

  mdc:
    name: "mdc"
    runs-on: "ubuntu-latest"
    steps:
      - name: "git checkout"
        uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0"  # v7.0.0
        with:
          fetch-depth: 0

      - name: "mlc"
        uses: "becheran/mlc@7ec24825cefe0c9c8c6bac48430e1f69e3ec356e"  # v1.2.0
        args: "--markup-types md"
