# Author:       Casey Sparks
# Date:         November 22, 2024
# Description:  Lint all markdown files with mdl (mdlint).
---
name: "markdown"
on:
  pull_request:
    branches: ["main"]
    paths: ["**/*.md"]
jobs:
  mdl:
    name: "mdl"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
    steps:
      - name: "git checkout"
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1"  # v7.0.1
        with:
          fetch-depth: 0

      - name: "mdl"
        uses: "actionshub/markdownlint@6c82ff529253530dfbf75c37570876c52692835f"  # v3.1.4

  mdc:
    name: "mdc"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
    steps:
      - name: "git checkout"
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1"  # v7.0.1
        with:
          fetch-depth: 0

      - name: "mlc"
        uses: "becheran/mlc@b0d0d353e04fcbcfd1d86716103d78a61e5b25dd"  # v1.2.2
        with:
          args: "--markup-types md"
