# Author:       Casey Sparks
# Date:         November 15, 2023
# Description:  Run dagger python checks.
---
name: "python"
on:
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.py"
      - "**/pyproject.toml"
      - "**/pylock.toml"
jobs:
  dagger_check_python:
    name: "dagger"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: "dagger check python:*"
        uses: "./.github/actions/dagger-check"
        with:
          check: "python:*"
