# Author:       Casey Sparks
# Date:         March 25, 2025
# Description:  Manage stale pull requests.
# Notes:        Refer to the [documentation](https://github.com/actions/stale).
---
name: "close stale pull requests"
on:
  schedule:
    - cron: "30 1 * * *"
permissions:
  actions: "write"
  contents: "write"  # For delete-branch option
  issues: "write"
  pull-requests: "write"
jobs:
  stale:
    name: "stale"
    runs-on: "ubuntu-latest"
    env:
      DAYS_TO_STALE: 28
    steps:
      - name: "close stale pull requests"
        uses: "actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899"  # v10.3.0
        with:
          repo-token: "${{ github.token }}"  # Global Settings
          days-before-stale: "${{ env.DAYS_TO_STALE }}"
          days-before-close: 7
          remove-stale-when-updated: true
          labels-to-remove-when-unstale: "stale"
          delete-branch: false
          stale-pr-label: "stale"  # PR settings
          exempt-pr-labels: "bot,dependabot,ignore-stale"
          close-pr-message: "This pull request has been closed because it was open for 21 days with no activity."
          stale-pr-message: |
            This pull request has been open for ${{ env.DAYS_TO_STALE }} days with no activity.
            It will be automatically closed in seven days unless you remove the 'stale' label.
            Add the 'ignore-stale' label to the pull request to disable future runs of this action.
          stale-issue-label: "stale"  # Issue settings
          exempt-issue-labels: "bot,dependabot,ignore-stale"
          close-issue-message: "This issue has been closed because it was open for 21 days with no activity."
          stale-issue-message: |
            This issue has been open for ${{ env.DAYS_TO_STALE }} days with no activity.
            It will be automatically closed in seven days unless you remove the 'stale' label.
            Add the 'ignore-stale' label to the pull request to disable future runs of this action.
