# Author:       Casey Sparks
# Date:         March 19, 2025
# Description:  Run Terraform operations to:
#                 1. Enumerate directories with changed Terraform files.
#                 2. Run tests against changed Terraform modules.
#                 3. Validate the syntax of changed Terraform manifests.
#                 4. Check the security posture of the changed Terraform
#                     modules and manifests.
#                 5. Generate a cost estimate of planned infrastructure changes
#                     and post the estimate to the pull request.
#                 6. Depending on if the event is a pull request or merge:
#                   a. On pull request: Plan infrastructure changes and comment
#                       the plan to the pull request.
#                   b. On merge: Deploy infrastructure changes.
---
name: "terraform"
on:
  push:
    branches: ["main"]
    paths:
      - "terraform/**/*.hcl"
      - "terraform/**/*.hcl.json"
      - "terraform/**/*.tf"
      - "terraform/**/*.tf.json"
      - "terraform/**/*.tfvars"
      - "terraform/**/*.tfvars.json"
  pull_request:
    branches: ["main"]
    paths:
      - "terraform/**/*.hcl"
      - "terraform/**/*.hcl.json"
      - "terraform/**/*.tf"
      - "terraform/**/*.tf.json"
      - "terraform/**/*.tfvars"
      - "terraform/**/*.tfvars.json"
env:
  TERRAFORM_PLANFILE: "/tmp/out.tfplan"
  TERRAFORM_VERSION: "1.15.6" # Increment to update Terraform
  INFRACOST_CONFIG: "terraform/infracost.yml"
jobs:
  changed_terraform:
    name: "Get changed Terraform directories"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
    outputs:
      manifest_dirs: "${{ steps.changed_manifests.outputs.tfmanifest_all_changed_files }}"
      module_dirs: "${{ steps.changed_modules.outputs.tfmodule_all_changed_files }}"
      all_dirs: "${{ steps.all_changed.outputs.tf_all_changed_dirs }}"
      infracost_updated: "${{ steps.changed_manifests.outputs.infracost_any_changed }}"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0" # v7.0.0
        with:
          fetch-depth: 2

      - name: "Get changed Terraform manifests"
        id: "changed_manifests"
        uses: "tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96" # 47.0.6
        with:
          files_yaml_from_source_file: ".github/config/changed_files.yml"
          matrix: true
          dir_names: true

      - name: "Get changed Terraform modules"
        id: "changed_modules"
        uses: "tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96" # 47.0.6
        with:
          files_yaml_from_source_file: ".github/config/changed_files.yml"
          matrix: true
          dir_names: true
          dir_names_max_depth: 3 # evaluates to ["terraform/modules/x","terraform/modules/y","terraform/modules/z"]

      - name: "Get all changed Terraform directories"
        id: "all_changed"
        run: |
          ALL_DIRS="$(                                                                          \
            echo                                                                                \
              '${{ steps.changed_manifests.outputs.tfmanifest_all_changed_files }}'             \
              '${{ steps.changed_modules.outputs.tfmodule_all_changed_files }}'                 \
            | jq -s '.[0] + .[1]'                                                               \
            | jq -r tostring                                                                    \
          )"

          echo "tf_all_changed_dirs=${ALL_DIRS}" >> "${GITHUB_OUTPUT}"

      - name: "Debug outputs"
        run: |
          printf 'manifest_dirs: ${{ steps.changed_manifests.outputs.tfmanifest_all_changed_files }}\n'
          printf 'module_dirs: ${{ steps.changed_modules.outputs.tfmodule_all_changed_files }}\n'
          printf 'all_dirs: ${{ steps.all_changed.outputs.tf_all_changed_dirs }}\n'
          printf 'infracost_updated: ${{ steps.changed_manifests.outputs.infracost_any_changed }}\n'

  terraform_test:
    name: "terraform test"
    runs-on: "ubuntu-latest"
    needs: ["changed_terraform"]
    # Runs on pull request if Terraform modules changed.
    if: "${{ github.event == 'pull_request' }}"
    permissions:
      contents: "read"
    strategy:
      max-parallel: 4
      matrix:
        dir: "${{ fromJSON(needs.changed_terraform.outputs.module_dirs) }}"
    defaults:
      run:
        working-directory: "${{ matrix.dir }}"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0" # v7.0.0
        with:
          fetch-depth: 2

      - name: "Install Terraform"
        uses: "hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e" # v4.0.1
        with:
          terraform_version: "${{ env.TERRAFORM_VERSION }}"

      - name: "terraform init"
        run: "terraform init --upgrade --backend=false" # Don't need backend for linting

      - name: "terraform test"
        run: "terraform test"

  terraform_validate:
    name: "terraform validate"
    runs-on: "ubuntu-latest"
    needs: ["changed_terraform"]
    # * Always runs on pull request
    # * Runs on push if Terraform manifests are changed
    if: "${{ needs.changed_terraform.outputs.manifest_dirs != '[]' }}"
    permissions:
      contents: "read"
    strategy:
      max-parallel: 4
      matrix:
        dir: "${{ fromJSON(needs.changed_terraform.outputs.all_dirs) }}"
    defaults:
      run:
        working-directory: "${{ matrix.dir }}"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0" # v7.0.0
        with:
          fetch-depth: 2

      - name: "Install Terraform"
        uses: "hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e" # v4.0.1
        with:
          terraform_version: "${{ env.TERRAFORM_VERSION }}"

      - name: "terraform init"
        run: "terraform init --upgrade --backend=false" # Don't need backend for linting

      - name: "terraform validate"
        run: "terraform validate"

  tfsec: # TODO: update to trivy
    name: "tfsec"
    runs-on: "ubuntu-latest"
    needs:
      - "changed_terraform"
      - "terraform_validate"
    # * Always runs on pull request if any terraform changed
    if: "${{ github.event == 'pull_request' }}"
    permissions:
      contents: "read"
    strategy:
      max-parallel: 4
      matrix:
        dir: "${{ fromJSON(needs.changed_terraform.outputs.all_dirs) }}"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0" # v7.0.0
        with:
          fetch-depth: 2

      - name: "tfsec"
        uses: "aquasecurity/tfsec-action@b466648d6e39e7c75324f25d83891162a721f2d6" # v1.0.3
        with:
          github_token: "${{ github.token }}"
          working_directory: "${{ matrix.dir }}"

  infracost_diff:
    name: "infracost diff"
    runs-on: "ubuntu-latest"
    needs:
      - "changed_terraform"
      - "terraform_validate"
    if: "${{ github.event_name == 'pull_request' && needs.changed_terraform.outputs.manifest_dirs != '[]' }}"
    permissions:
      contents: "read"
      pull-requests: "write"
    env:
      COMMENT: "!!!WARNING!!! Terraform manifests updated, but Infracost files remain untouched."
    steps:
      - name: "Find Existing Comment"
        if: "${{ needs.changed_terraform.outputs.infracost_updated == 'false' }}"
        uses: "peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad" # v4.0.0
        id: "find_comment"
        with:
          issue-number: "${{ github.event.pull_request.number || github.event.issue.number }}"
          comment-author: "github-actions[bot]"
          body-includes: "${{ env.COMMENT }}"

      - name: "Post nag reminder"
        if: "${{ needs.changed_terraform.outputs.infracost_updated == 'false' }}"
        uses: "actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3" #v9.0.0
        with:
          script: |
            const comment_id = '${{ steps.find_comment.outputs.comment-id }}';
            const body = '${{ env.COMMENT }}';

            if (comment_id) {
              // Update the existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment_id,
                body: body
              });
            } else {
              // Create a new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body
              });
            }

      - name: "git checkout"
        if: "${{ needs.changed_terraform.outputs.infracost_updated == 'true' }}"
        uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0"  # v7.0.0
        with:
          fetch-depth: 0
          ref: "${{ github.event.pull_request.base.ref }}"

      - name: "Setup Infracost"
        if: "${{ needs.changed_terraform.outputs.infracost_updated == 'true' }}"
        uses: "infracost/actions/setup@fb736a8f219195d6efdca58682069b16fe1bc280"  # v4.2.0
        with:
          api-key: "${{ secrets.INFRACOST_API_KEY }}"
          github-token: "${{ github.token }}"

      - name: "infracost breakdown (baseline)"
        if: "${{ needs.changed_terraform.outputs.infracost_updated == 'true' }}"
        run: >
          infracost breakdown                                                 \
            --config-file ${{ env.INFRACOST_CONFIG }}                         \
            --format json                                                     \
            --out-file /tmp/infracost_base.json

      - name: "git checkout (pr branch)"
        if: "${{ needs.changed_terraform.outputs.infracost_updated == 'true' }}"
        uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0"  # v7.0.0
        with:
          fetch-depth: 0

      - name: "infracost diff"
        if: "${{ needs.changed_terraform.outputs.infracost_updated == 'true' }}"
        run: >
          infracost diff                                                      \
            --config-file ${{ env.INFRACOST_CONFIG }}                         \
            --format json                                                     \
            --compare-to /tmp/infracost_base.json                             \
            --out-file /tmp/infracost_diff.json

      - name: "infracost comment"
        if: "${{ needs.changed_terraform.outputs.infracost_updated == 'true' }}"
        run: >
          infracost comment github                                            \
            --path /tmp/infracost_diff.json                                   \
            --repo ${{ github.repository }}                                   \
            --pull-request ${{ github.event.pull_request.number }}            \
            --github-token ${{ github.token }}                                \
            --behavior update

  terraform_plan_apply:
    name: "terraform plan && terraform apply"
    runs-on: "ubuntu-latest"
    # Runs on both PR+push if Terraform manifests change
    if: "${{ needs.changed_terraform.outputs.manifest_dirs != '[]' }}"
    needs:
      - "changed_terraform"
      - "terraform_validate"
    permissions:
      contents: "read"
      pull-requests: "write"
      id-token: "write"
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        dir: "${{ fromJSON(needs.changed_terraform.outputs.manifest_dirs) }}"
    defaults:
      run:
        working-directory: "${{ matrix.dir }}"
    concurrency:
      group: "${{ github.workflow-}}-${{ github.ref_name }}-terraformplanapply-${{ matrix.dir }}"
      cancel-in-progress: false
    steps:
      - name: "Checkout"
        uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0" # v7.0.0
        with:
          fetch-depth: 2

      - name: "Install Terraform"
        uses: "hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e" # v4.0.1
        with:
          terraform_version: "${{ env.TERRAFORM_VERSION }}"

      - name: "aws sso login"
        uses: "aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b"  # v6.2.1
        with:
          aws-region: "${{ secrets.AWS_REGION }}"
          role-to-assume: "${{ secrets.AWS_ROLE_ARN }}"

      - name: "terraform init"
        run: "terraform init --upgrade"

      - name: "terraform plan"
        run: "terraform plan -out=${TERRAFORM_PLANFILE}"

      - name: "Post PR comment"
        if: "${{ github.event_name == 'pull_request' }}"
        uses: "borchero/terraform-plan-comment@2d41e908725447b1677913001dfb92fa7010c025"  # v3.1.0
        with:
          token: "${{ github.token }}"
          planfile: "${{ env.TERRAFORM_PLANFILE }}"
          terraform-cmd: "terraform"
          working-directory: "${{ matrix.dir }}"
          header: "Terraform Plan"
          skip-comment: false
          skip-empty: false
          expand-comment: false

      - name: "terraform apply"
        if: "${{ github.event_name == 'push' }}"
        run: "terraform apply --auto-approve ${TERRAFORM_PLANFILE}"
